### ISSUE TITLE
As Coordinator, I want to create , edit, remove a new student / teacher account

### ISSUE THREAD

**Issue by ronanpnc** [pnc-virtual-company/2022-G4-VC2-PART2#11]

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/189519272-99b0b26c-49da-47d6-a3eb-6739a98d4f17.png)

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/189519314-6f16a9a6-daad-44be-b47f-52c003655b05.png)

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/189519334-1b2ad95e-a155-43c8-8190-becdd14e9699.png)

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/189519351-dbc1ba31-11d6-4419-9471-499b0a584360.png)

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/189519376-807482d1-4114-4b89-a344-a3d20085a085.png)

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/189519407-81517d35-612a-4d9b-8094-5ca9cc21eedc.png)

**Comment by ronanpnc** [comment]
In term of wireframes it looks good!
