### ISSUE TITLE
Display the  detailed informtion about teacher/student when clicking on item using an accordion widget

### ISSUE THREAD

**Issue by nga-hoeun** [pnc-virtual-company/2022-G4-VC2-PART2#21]
mock needed !

**Comment by ronanpnc** [comment]
@HAK-KIM  HAK HAK ! could you provide the mock up for this dialog and have it validated by customer ?

**Comment by ronanpnc** [comment]
we will use an Tailwind  accordeon tfor this feature

**Comment by HAK-KIM** [comment]
![Image](https://user-images.githubusercontent.com/90229497/190841736-f844233d-b518-4fbf-95af-10d3a2658cd4.png)



![Image](https://user-images.githubusercontent.com/90229497/190841752-769c7f9d-82bc-4df6-8dd4-9542a0bf64f5.png)
