### ISSUE TITLE
Follow up list  view

### ISSUE THREAD

**Issue by nga-hoeun** [pnc-virtual-company/2022-G4-VC2-PART2#36]
List of students who are in the followup
"/listFollowUp"

this view shoudl also add a main button to add a studnet to the list

**Comment by kimhak-hello** [comment]
![image](https://user-images.githubusercontent.com/90994316/191407667-5d03c525-a670-4cfe-9b9b-c473250b4a4e.png)

**Comment by kimhak-hello** [comment]
![image](https://user-images.githubusercontent.com/90994316/191407741-468640e9-b1ff-41f5-abf9-c9728dc5891a.png)
